const INIT_PAGINATION = 'INIT_PAGINATION';
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCT = 'GET_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_PRODUCT = 'SET_PRODUCT';
const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
const RESET = 'RESET';
const ERROR = 'ERROR';
const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
const SET_PAGINATION_MAX_PAGES = 'SET_PAGINATION_MAX_PAGES';
const SET_PAGINATION_MAX_ITEMS = 'SET_PAGINATION_MAXITEMS';

export {
    INIT_PAGINATION,
    GET_PRODUCTS,
    GET_PRODUCT,
    SET_PRODUCTS,
    SET_PRODUCT,
    UPDATE_PRODUCTS,
    RESET,
    ERROR,
    SET_PAGINATION_PAGE,
    SET_PAGINATION_MAX_PAGES,
    SET_PAGINATION_MAX_ITEMS,
    DELETE_PRODUCT
}